### ISSUE TITLE
Add BRANCH field in issue tab

### ISSUE THREAD

**Issue by ulgaia** [MeetMe/jira-gerrit-plugin#12]
Hello,

It would be nice to be able to see the BRANCH directly in the issue tab below the 'Project' field. Even better would be the ability to configure some gerrit reviews field to display in this tab (but that may ba an overkill though).

![branch section added in gerrit reviews tab](https://cloud.githubusercontent.com/assets/7942164/3338880/2514f496-f862-11e3-8809-6f9331603f92.png)

**Comment by buenjybar** [comment]
this will be a great enhancement.
:+1:

**Comment by aurobindo1986** [comment]
Hi Team,

Let us know if you have any update on this.

**Comment by 0to** [comment]
@aurobindo1986 
The latest version 3.2 adds the review's target branch to the Gerrit Reviews tab panel.
