### ISSUE TITLE
PlugIn compilation question

### ISSUE THREAD

**Issue by vrtareg** [MeetMe/jira-gerrit-plugin#13]
Hi Team

I am not sure if I am writing to the right person so sorry if this is the wrong mail.

We are trying to compile and improve your Gerrit PlugIn for Jira and see if we can add the multirepository option in it.

We are facing some troubles with compiling and I am thinking that we are missing something in configuration or in additional required packages.

I would like to kindly ask you if you can help us with some guidance how to do the configuration like which additional packages or additional jar files to add to the Atlassian SDK in order to get the plugin compiled and running.

Thank you very much in advance for any help.

P.S.

I hope links that I got are correct:

https://github.com/MeetMe/jira-gerrit-plugin
https://marketplace.atlassian.com/plugins/com.meetme.plugins.jira.gerrit-plugin

Not sure about this one:
http://repo.jenkins-ci.org/releases/com/sonyericsson/hudson/plugins/gerrit/gerrit-events/1.5.2/
and some other dependicies.

Regards,
Areg

**Comment by jhansche** [comment]
@vrtareg is this still an issue?  Last I heard from your colleague Curtis, it was compiling successfully.

**Comment by vrtareg** [comment]
Hi

Sorry we did not updated you.

He was able to compile the project and actually redesigned it completely to include multi repository and also he was able to read GIT log without checking out whole repository,

May be he will think about sharing the code once completed.

Regards,
Areg
