### ISSUE TITLE
Be able to restrict viewing of reviews by permission

### ISSUE THREAD

**Issue by rburgst** [MeetMe/jira-gerrit-plugin#14]
It would be good to be able to require users to have a specific permission such as "view development tools" in order to see the code.

**Comment by jhansche** [comment]
The code is contained in the Gerrit instance, not in JIRA.  The only thing that JIRA exposes is the summary and links to the Gerrit reviews.  To restrict access to Gerrit, you need to configure Gerrit's access controls.
