### ISSUE TITLE
compatibility with jira data center

### ISSUE THREAD

**Issue by mtuanp** [MeetMe/jira-gerrit-plugin#17]
Please make the gerrit plugin compatible with jira data center edtion.

**Comment by jhansche** [comment]
Is this not the standard, typical installation of JIRA?  Are you referring to [JIRA Cloud](https://confluence.atlassian.com/display/Cloud/JIRA+Cloud)?

We run JIRA in our own data center, and have done so for several years.  The plugin was developed for that type of installation.  Are you having problems with it?

**Comment by mtuanp** [comment]
No, is not a standard installation from jira. [Jira data center](https://www.atlassian.com/enterprise/data-center) is jira for a cluster server environment. For more information about jira data center plugin development follow this  [link](https://developer.atlassian.com/market/developing-for-the-marketplace/data-center-add-on-development).

**Comment by jhansche** [comment]
Gotcha...  I have not heard of this.  If you want to try compiling it with the suggested support tag in the descriptor and see if it works, that would be an easy change.  But if it requires more refactoring to support a clustered environment, it may take a bit more time to get around to this.

**Comment by iphil** [comment]
Any progress on this issue? Did anyone tried this in a datacenter cluster.

**Comment by jhansche** [comment]
This has not been a priority for me, as I do not use JIRA Data Center.  If someone else would like to look into what is required to enable that support, you're more than welcome to do so.

The link that @mtuanp gave mentions simply adding a compatibility flag to the plugin descriptor.  But I would want to test how the plugin behaves in the cluster configuration before I'd be confident in deploying it, and I simply don't have the time to set up the test environment for that.

If anyone else would like to test that, and report back with specific bugs (or better yet, fix them!), that would make things easier.

**Comment by savaikar** [comment]
Hello Joe,

A very happy new year to you.

Any updates on this would be quite helpful for us as we use the JIRA Data Center edition.

Thanks and Regards,
Rahul

**Comment by jhansche** [comment]
Nothing has changed since my last comment. My company doesn't use JIRA Data Center, so I haven't had time to investigate this. I've left the issue open for that reason, and I welcome outside contributions.  Feel free to work on adding that support and testing it with your own JIRA instance.

**Comment by mtuanp** [comment]
Hi Guys,

my customer using JIRA 6.4 DC with 3 JIRA Nodes. We using the Gerrit Plugin version 2.3 and it works fine. I also reviewed the Gerrit Plugin Codebase on version 2.3 and I can tell the plugin is DC-compatible.

Thanks and Regards,
Tuan

**Comment by jhansche** [comment]
@mtuanp being that I am not familiar with JIRA DC, and it sounds like you've already tested it, would you like to submit a PR to enable that? I'll gladly merge it, the only thing I've been asking for was for someone to test it out on a DC installation.

**Comment by mtuanp** [comment]
Yes we tested on JIRA DC with 3 Nodes and actually it runs on our production server without problems.

**Comment by jhansche** [comment]
Thank you for the PR @mtuanp!

I'll look into getting this released soon

**Comment by jhansche** [comment]
Plugin version 3.2 has been released with JIRA Data Center compatibility: https://marketplace.atlassian.com/plugins/com.meetme.plugins.jira.gerrit-plugin/versions#b67
