### ISSUE TITLE
IOException thrown when trying to add a private key to the plugin settings

### ISSUE THREAD

**Issue by lscarval** [MeetMe/jira-gerrit-plugin#22]
Without the key file everything works fine. When I pick an id_rsa file to be added to the settings, it throws the exception below:

java.io.IOException: No such file or directory at java.io.UnixFileSystem.createFileExclusively(Native Method) at java.io.File.createTempFile(Unknown Source) at com.meetme.plugins.jira.gerrit.adminui.AdminServlet.doUploadPrivateKey(AdminServlet.java:187) at com.meetme.plugins.jira.gerrit.adminui.AdminServlet.doPost(AdminServlet.java:130) at javax.servlet.http.HttpServlet.service(HttpServlet.java:646) at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) at

**Comment by lscarval** [comment]
This issue is resolved by this Pull request: https://github.com/MeetMe/jira-gerrit-plugin/pull/23

**Comment by jhansche** [comment]
Thanks for the PR!
