### ISSUE TITLE
Moving a JIRA issue from one project to another project makes all linked commits in 'Gerrit Reviews'-tab disappear.

### ISSUE THREAD

**Issue by itruls** [MeetMe/jira-gerrit-plugin#25]
We have a project named 'OLD' in Jira with several issues. Some of these issues belong to another project NEW, and are moved from OLD to NEW.
E.g.: The gerrit commit message is: OLD-1: Fixed bug.
In the jira-issue OLD-1 the commit is displayed in 'Gerrit Reviews'
After moving issue OLD-1 to NEW-3 (but not changing the commit message since it is already merged to master), the commit is no longer displayed under 'Gerrit Reviews' for jira-issue NEW-3 (number 3 since there was already two issues created in project NEW). This might seem obvious, but if you go to http://jira/browse/OLD-1 you are redirected to the new location http://jira/browse/NEW-3. Is it possible for the Gerrit plugin to handle this rename, so that commit OLD-1 is displayed under issue NEW-3.

**Comment by jhansche** [comment]
I'm not sure that JIRA has a way to indicate all old/previous names by which a given issue has previously been known.  It would be possible to aggregate multiple names for an issue, if we know that it has been moved in the past.

**Comment by pavel-tarasenko** [comment]
Pull request #33 should be able to address the issue :-)

**Comment by jhansche** [comment]
Version 3.1 was just released, including @pavel-tarasenko's fix from PR #33.
https://marketplace.atlassian.com/plugins/com.meetme.plugins.jira.gerrit-plugin/versions#b57
