### ISSUE TITLE
Saving Gerrit Settings, showing "Private Key is already on file. Upload a new one to replace it. "

### ISSUE THREAD

**Issue by cwyywc** [MeetMe/jira-gerrit-plugin#29]
I am doing the Gerrit Setting on JIRA 7.0.0. But I can not test the config because there is no information showing and action after I click the "Test Config" Button. And the message "Private Key is already on file. Upload a new one to replace it. " shows after I click "Save" Button. 

Attachment has the detail configuration for Gerrit and it shows the message above. 
And there is another capture for that I have test below ssh command on my server and it is OK . So that prove the ssh setting do not have problem . 

So could you pls kindly advise where is wrong for the Gerrit Setting? Thanks for your kindly help. 
I am sorry that I can not update the attachment. But below is the detail configuration and ssh command which I have tested on my server 
SSH Host:172.25.43.10
SSH Port: 29418
SSH Username:testuser03

ssh -p 29418 -i ~/.ssh/testuser03 172.25.43.10 -l testuser03

**Comment by jhansche** [comment]
**This is not an error!**

It is only there to inform you that you **do not** have to do anything in the SSH Key field, unless you want to *change* the SSH key. Just ignore that message and the field entirely, if you don't need to change it.
