### ISSUE TITLE
Enable Gerrit Reviews session per-project or per-project-category

### ISSUE THREAD

**Issue by gnustavo** [MeetMe/jira-gerrit-plugin#31]
Now that the Gerrit Reviews tab was replaced by the Gerrit Reviews session on the issue view it's much more visible. But I think it's normal to have non-software related projects in JIRA. In my installation we have about 400+ projects, 1/3 of which aren't software related. So, for those projects, the Gerrit Reviews doesn't make sense and confuse/annoy their users.

It would be great if we could enable the Gerrit Reviews session in one of these three ways:
- for all projects
- for specific project categories (multi-selection menu)
- for specific projects (multi-selection menu)

I found [this answer](https://answers.atlassian.com/questions/32506164/disable-jira-gerrit-plugin-on-a-per-project-basis) in Atlassian Answers asking for this, but I couldn't find any issues yet.

Thanks!

**Comment by mikejr83** [comment]
This is also important for our organization as well. I've been able to get users to click the hide arrow, but it would be better to have this section be enabled/disabled by project owners or administrators. I believe the SVN plugin from Jira has similar functionality to what is described.

**Comment by jhansche** [comment]
Version 3.1 of the plugin was just released:
https://marketplace.atlassian.com/plugins/com.meetme.plugins.jira.gerrit-plugin/versions#b57
This version includes an option on the admin configuration page to suppress the web panel if there are zero matching reviews.

Note that "matching" includes both open and closed (merged/abandoned) reviews:  so if there's absolutely nothing in Gerrit matching the query, then the panel will be suppressed when the new checkbox is unchecked.  But if there is a matching closed review, and your filter options have been selected to only show open reviews, the panel will still appear, allowing you to change your filter options to show/hide those closed reviews.
