### ISSUE TITLE
Restrict Gerrit Reviews Web Panel to certain projects and issue types

### ISSUE THREAD

**Issue by glewe** [MeetMe/jira-gerrit-plugin#38]
Once the Gerrit plugin is enabled, the Gerrit Reviews Web Panel shows on every issue. This effect might not be desired for those instances that run projects for wich code reviews are not applicable.

Thus, my feature request would be to offer a list of project and issue types on the configuration page that the panel can be restricted to.

Thanks for your work, Best regards,
George

**Comment by jhansche** [comment]
While this does not implement the fix as requested here, the 3.1 release now includes an option in the admin configuration page to remove the panel if there are no matching issues.

Note that if the query does return non-open reviews (abandoned or already merged), but there are 0 _open_ reviews, and you've set the filter option to only show open reviews, the panel will still appear, allowing you to change the filter option to show all.

But if there are 0 reviews matching the issue key, open or closed, the panel will be omitted entirely.

Please try out the 3.1 release and see if that suits your needs: https://marketplace.atlassian.com/plugins/com.meetme.plugins.jira.gerrit-plugin/versions#b57
