### ISSUE TITLE
Allow disabling Gerrit Reviews panel for certain projects

### ISSUE THREAD

**Issue by borgeorgiev** [MeetMe/jira-gerrit-plugin#43]
It would be nice to have a way to disable the Gerrit integration for some projects, since not all projects in the same JIRA instance might be development projects.
The panel is confusing some of the users in non-dev projects/issues.

This can be achieved by adding a global configuration, allowing you to turn-off gerrit integration per-project basis

**Comment by Jakohbae** [comment]
See https://github.com/MeetMe/jira-gerrit-plugin/pull/57

**Comment by jhansche** [comment]
The PR has been merged and will be available in the next release.
