### ISSUE TITLE
Number of changes shown

### ISSUE THREAD

**Issue by fstefanov** [MeetMe/jira-gerrit-plugin#46]
Is this plugin showing only up to 3 changes?
I have 4 changes opened for the same Jira issue.
All changes have identical jira ticket inserted in the commit message.
Inside my ticket i see 3 changes, the oldest one which is already merged is missing.
Regards.

**Comment by jhansche** [comment]
In the top-right corner of the Gerrit Reviews web panel, you'll find a down-arrow (▾) with tooltip "Options".  In there, you can choose "Show All Reviews" or "Show Open Reviews"

Please try changing that and see if it solves your issue.
