### ISSUE TITLE
Fetch the existing Gerrit Reviews data using the REST or Export to CSV

### ISSUE THREAD

**Issue by balug12** [MeetMe/jira-gerrit-plugin#72]
I would like to know if it feasible to fetch the existing Gerrit Reviews data which are associated with  given issue key, either using the REST API Call or via exporting to  CSV file in JIRA
I see that  comments get exported to CSV when i export the issue however the Gerrit reviews won't get exported.

**Comment by jhansche** [comment]
You can do this using either the SSH query command, or the REST API:
https://gerrit-review.googlesource.com/Documentation/cmd-query.html
https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#list-changes

There's no need to add this to the plugin.
