### ISSUE TITLE
Release current version to Atlassian Marketplace

### ISSUE THREAD

**Issue by finger42** [MeetMe/jira-gerrit-plugin#80]
Hello,

I would like to use this cool plugin in my environment.

Is it possible to release the current version to the Atlassian Marketplace?

I think this would help a lot spread the plugin more.

**Comment by jhansche** [comment]
The plugin has always been in the marketplace:
https://marketplace.atlassian.com/apps/1210874/gerrit-code-review-for-jira?tab=overview&hosting=server

It's also mentioned and linked just one short click away, in this project's readme: https://github.com/MeetMe/jira-gerrit-plugin#install
