### ISSUE TITLE
Is it possible to Filter in Jira after issues that have Gerrit Review Links

### ISSUE THREAD

**Issue by vinczepaula** [MeetMe/jira-gerrit-plugin#83]
Hello,
Is it possible to Filter in Jira after issues that have Gerrit Review Links ?
See similar question here.
https://community.atlassian.com/t5/Marketplace-Apps-Integrations/Filter-issues-with-Gerrit-Review-links/qaq-p/1314311

**Comment by vinczepaula** [comment]
Is there any news about this question ?

**Comment by philipp-luettecke** [comment]
Hi @vinczepaula,
I'm also looking for a solution here.
I'm looking for either a Jira Structure Formula, or even better a JQL query to look for Gerrit Review Links.

@jhansche is there any option for this?`

Thanks!

**Comment by jhansche** [comment]
No, the plugin queries gerrit only when you view an issue. There is no central storage of all known reviews and the issues they mention. Without that, there would be no way to implement this filter.

Maybe you'd have better luck trying to filter the other way? Use gerrit search predicates to find what you need, and extract Jira issues from those.
